### ISSUE TITLE
 in addition The 3DO Company-3DO (4DO)? Gamepad does not work in the emulator (xbox360)

### ISSUE THREAD

**Issue by Sidordroid** [kodi-game/game.libretro.opera#8]
![screenshot000](https://user-images.githubusercontent.com/71819151/94144329-aae73b00-fe79-11ea-9932-c84613089d94.png)
![screenshot005](https://user-images.githubusercontent.com/71819151/94144336-ac186800-fe79-11ea-8ab3-8bac692835a5.png)

Does anyone play on CoreElec in addition to The 3DO Company-3DO (4DO)? Here the gamepad (xbox360) does not work in the emulator. It is not detected. Writes, there is nothing to assign and the buttons in the emulator do not work. The emulator itself set up with grief in half, I climbed a few days on-speaking forums to find out how to register the correct configs and paths. I didn't find anything about a non-working gamepad. Can I tweak which config where?[

**Comment by eigendude** [comment]
I wrote the input code, so if there's a not working gamepad it's my fault :slightly_smiling_face: can you upload a debug log please?

**Comment by Sidordroid** [comment]
> I wrote the input code, so if there's a not working gamepad it's my fault  can you upload a debug log please?

What debug mode, how to enable it, what input code and where can I download it?

**Comment by garbear** [comment]
> What debug mod

See https://kodi.wiki/view/Log_file

> what input code

I wrote the gamepad code that you are currently running on your computer (that was my work account). You already have it.

**Comment by Sidordroid** [comment]
> I wrote the gamepad code that you are currently running on your computer (that was my work account). You already have it.

I don’t have any code, I don’t understand this at all, the log file is also a hemorrhoid option. Why not make the gamepad settings simpler like in other emulators? I still can’t play because of the inoperative control. Please fix it in the next updates

**Comment by garbear** [comment]
You're using a third-party skin. Does this fully support the controller dialog? Please try with the Estuary skin of the latest Kodi nightly.

If we can figure out what's wrong I can try and fix it.

**Comment by Sidordroid** [comment]
> Вы используете сторонний скин. Это полностью поддерживает диалог контроллера? Пожалуйста, попробуйте использовать скин Estuary из последней версии Kodi nightly.
> 
> Если мы сможем выяснить, что не так, я попробую исправить это.


I am using Coreelec 9.2.4.2 and Kodi 18.8 and I am not able to change or update anything on this system

**Comment by Sidordroid** [comment]
> Вы используете сторонний скин. Это полностью поддерживает диалог контроллера? Пожалуйста, попробуйте использовать скин Estuary из последней версии Kodi nightly.
> 
> Если мы сможем выяснить, что не так, я попробую исправить это.

**Comment by Sidordroid** [comment]
> You're using a third-party skin. Does this fully support the controller dialog? Please try with the Estuary skin of the latest Kodi nightly.
> 
> If we can figure out what's wrong I can try and fix it.


I am using Coreelec 9.2.4.2 and Kodi 18.8 and I am not able to change or update anything on this system

**Comment by garbear** [comment]
If not too much trouble, could you try LibreELEC? That distro uses Estuary. It would be good to narrow this problem down to see if it is a skin issue with CoreELEC.

**Comment by Sidordroid** [comment]
> If not too much trouble, could you try LibreELEC? That distro uses Estuary. It would be good to narrow this problem down to see if it is a skin issue with CoreELEC.

The fact of the matter is that I cannot install other operating systems besides CoreElec. I have Amlogic S905X3 and nothing is supported by this processor

**Comment by Sidordroid** [comment]
Here are the logs, I don’t know if I took them off correctly, I just took out what was in the Logfiles folder. Based on their results, it may turn out to solve the problem with non-working gamepads
[log-2020-09-17-17.53.36.zip](https://github.com/kodi-game/game.libretro.opera/files/5602245/log-2020-09-17-17.53.36.zip)
[log-2020-10-10-08.33.45-FAILED.zip](https://github.com/kodi-game/game.libretro.opera/files/5602246/log-2020-10-10-08.33.45-FAILED.zip)
[log-2020-11-15-11.33.40.zip](https://github.com/kodi-game/game.libretro.opera/files/5602247/log-2020-11-15-11.33.40.zip)
[log-2020-11-15-11.34.18.zip](https://github.com/kodi-game/game.libretro.opera/files/5602248/log-2020-11-15-11.34.18.zip)
[log-2020-11-15-11.34.31.zip](https://github.com/kodi-game/game.libretro.opera/files/5602249/log-2020-11-15-11.34.31.zip)
[log-2020-11-15-11.35.24.zip](https://github.com/kodi-game/game.libretro.opera/files/5602250/log-2020-11-15-11.35.24.zip)
[log-2020-11-15-12.56.46.zip](https://github.com/kodi-game/game.libretro.opera/files/5602251/log-2020-11-15-12.56.46.zip)
[log-2020-11-15-12.57.21.zip](https://github.com/kodi-game/game.libretro.opera/files/5602252/log-2020-11-15-12.57.21.zip)
[log-2020-11-15-12.57.44.zip](https://github.com/kodi-game/game.libretro.opera/files/5602253/log-2020-11-15-12.57.44.zip)
[log-2020-11-15-12.58.29.zip](https://github.com/kodi-game/game.libretro.opera/files/5602254/log-2020-11-15-12.58.29.zip)
[log-2020-11-15-12.58.57.zip](https://github.com/kodi-game/game.libretro.opera/files/5602255/log-2020-11-15-12.58.57.zip)
[log-2020-11-15-12.59.22.zip](https://github.com/kodi-game/game.libretro.opera/files/5602256/log-2020-11-15-12.59.22.zip)
[log-2020-11-15-12.59.41.zip](https://github.com/kodi-game/game.libretro.opera/files/5602257/log-2020-11-15-12.59.41.zip)
[log-2020-11-15-13.00.52.zip](https://github.com/kodi-game/game.libretro.opera/files/5602258/log-2020-11-15-13.00.52.zip)
[log-2020-11-15-13.14.10.zip](https://github.com/kodi-game/game.libretro.opera/files/5602259/log-2020-11-15-13.14.10.zip)
[log-2020-11-15-13.14.31.zip](https://github.com/kodi-game/game.libretro.opera/files/5602260/log-2020-11-15-13.14.31.zip)
[log-2020-11-17-06.20.23.zip](https://github.com/kodi-game/game.libretro.opera/files/5602261/log-2020-11-17-06.20.23.zip)
[log-2020-11-17-06.22.37.zip](https://github.com/kodi-game/game.libretro.opera/files/5602262/log-2020-11-17-06.22.37.zip)
[log-2020-11-17-06.22.54.zip](https://github.com/kodi-game/game.libretro.opera/files/5602263/log-2020-11-17-06.22.54.zip)
[log-2020-11-17-06.23.18.zip](https://github.com/kodi-game/game.libretro.opera/files/5602264/log-2020-11-17-06.23.18.zip)
[log-2020-11-17-06.24.00.zip](https://github.com/kodi-game/game.libretro.opera/files/5602265/log-2020-11-17-06.24.00.zip)
[log-2020-11-17-06.24.40.zip](https://github.com/kodi-game/game.libretro.opera/files/5602266/log-2020-11-17-06.24.40.zip)
[log-2020-11-17-06.49.58.zip](https://github.com/kodi-game/game.libretro.opera/files/5602267/log-2020-11-17-06.49.58.zip)
[log-2020-11-17-06.50.23.zip](https://github.com/kodi-game/game.libretro.opera/files/5602269/log-2020-11-17-06.50.23.zip)
[log-2020-11-17-06.50.42.zip](https://github.com/kodi-game/game.libretro.opera/files/5602270/log-2020-11-17-06.50.42.zip)
[log-2020-11-17-06.50.55.zip](https://github.com/kodi-game/game.libretro.opera/files/5602271/log-2020-11-17-06.50.55.zip)
[log-2020-11-19-10.50.51.zip](https://github.com/kodi-game/game.libretro.opera/files/5602272/log-2020-11-19-10.50.51.zip)
[log-2020-11-19-10.51.15.zip](https://github.com/kodi-game/game.libretro.opera/files/5602273/log-2020-11-19-10.51.15.zip)
[log-2020-11-26-10.26.27.zip](https://github.com/kodi-game/game.libretro.opera/files/5602274/log-2020-11-26-10.26.27.zip)
